package Client.View;

import Client.Controller.Client;
import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;

/**
 * Add a user dialog
 */
public class addUserGUI extends JDialog {
	private JPanel contentPane;
	private JButton buttonOK;
	private JButton buttonCancel;
	private JTextField username;
	private JLabel userNameLabel;
	private JPasswordField passwordField1;
	private JLabel accessLevelLabel;
	private JComboBox comboBox1;
	private Client client;

	public addUserGUI(Client client) {



		this.client = client;
		try {
			JSONObject accountTypes = client.getAccountTypes();
			JSONArray arrayOfTypes = accountTypes.getJSONArray("levels");
			System.out.println(accountTypes.length());
			for (int i = 0; i < accountTypes.length()+1; i++) {
				comboBox1.addItem(new AccessLevel(arrayOfTypes.getJSONObject(i).getInt("typeId"),arrayOfTypes.getJSONObject(i).getString("typeName")));
			}

		} catch (IOException e) {
			e.printStackTrace();
		}

		setContentPane(contentPane);
		setModal(true);
		getRootPane().setDefaultButton(buttonOK);

		buttonOK.addActionListener(e -> onOK());

		buttonCancel.addActionListener(e -> onCancel());

		// call onCancel() when cross is clicked
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				onCancel();
			}
		});

		// call onCancel() on ESCAPE
		contentPane.registerKeyboardAction(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				onCancel();
			}
		}, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
	}

	/**
	 * Add user
	 */
	private void onOK() {
		// add your code here
		String usernameString = username.getText();
		String passwordString = new String(passwordField1.getPassword());
		AccessLevel type = (AccessLevel) comboBox1.getSelectedItem();
		try {
			JSONObject returnJSON =client.addUser(usernameString,passwordString,type.getId());
			if(returnJSON.getBoolean("success")) {
				JOptionPane.showMessageDialog(this,
						"User added","Success",JOptionPane.PLAIN_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this,
						"Username already in use",
						"Error",
						JOptionPane.ERROR_MESSAGE);
			}
			System.out.println(returnJSON.toString());
		} catch (IOException e) {
			e.printStackTrace();
		}
		dispose();
	}

	/**
	 * cancel adding user
	 */
	private void onCancel() {
		// add your code here if necessary
		dispose();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridBagLayout());
		contentPane.setMinimumSize(new Dimension(300, 500));
		contentPane.setPreferredSize(new Dimension(300, 300));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(panel1, gbc);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(panel2, gbc);
		buttonOK = new JButton();
		buttonOK.setText("OK");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(buttonOK, gbc);
		buttonCancel = new JButton();
		buttonCancel.setText("Cancel");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(buttonCancel, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel2.add(spacer1, gbc);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridBagLayout());
		panel3.setMinimumSize(new Dimension(300, 200));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(panel3, gbc);
		userNameLabel = new JLabel();
		userNameLabel.setHorizontalAlignment(10);
		userNameLabel.setText("Username ");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(userNameLabel, gbc);
		username = new JTextField();
		username.setColumns(10);
		username.setHorizontalAlignment(10);
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		panel3.add(username, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel3.add(spacer2, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Password ");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(label1, gbc);
		passwordField1 = new JPasswordField();
		passwordField1.setColumns(10);
		passwordField1.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel3.add(passwordField1, gbc);
		accessLevelLabel = new JLabel();
		accessLevelLabel.setText("Access Level ");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel3.add(accessLevelLabel, gbc);
		comboBox1 = new JComboBox();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel3.add(comboBox1, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel3.add(spacer3, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Add new user:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		contentPane.add(label2, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

}
